name: Auto-Async

on:
  push:
  workflow_dispatch:
  schedule:
    #自动同步：每天早上1点
    - cron: 0 * * * *
  watch:
    types: [started]

permissions:
  contents: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Projects
        uses: actions/checkout@master

      - name: Cache Clean
        run: gh cache delete --all
  merge:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Merge upstream
        run: |
          git config --global user.name 'laosan-xx'
          git config --global user.email 'xxhy1989@gmail.com'
          git pull --unshallow
          git remote add upstream https://github.com/Loyalsoldier/surge-rules.git
          git fetch upstream
          git checkout master
          git merge --no-edit upstream/master
          git push origin master
